### ISSUE TITLE
Day is always Sunday in a date field

### ISSUE THREAD

**Issue by tvjon** [bakulf/libmrss#1]
I've been testing rsstail which uses libmrss, & noticed that feeds where I specified the date to be displayed display the correct date & time, but always Sunday as the day.

https://github.com/flok99/rsstail/issues/28

**Comment by Necior** [comment]
@bakulf, I'm glad to see the fix :)

(As we mailed I planned to take care of this issue but a lot of stuff is going on lately. I'm sorry.)
